INFO: encountered (<pyang.error.Position object at 0x6fffe547c30>, 'UNUSED_IMPORT', u'ietf-yang-types')
# -*- coding: utf-8 -*-
from operator import attrgetter
import pyangbind.lib.xpathhelper as xpathhelper
from pyangbind.lib.yangtypes import RestrictedPrecisionDecimalType
from pyangbind.lib.yangtypes import RestrictedClassType
from pyangbind.lib.yangtypes import TypedListType
from pyangbind.lib.yangtypes import YANGBool
from pyangbind.lib.yangtypes import YANGListType
from pyangbind.lib.yangtypes import YANGDynClass
from pyangbind.lib.yangtypes import ReferenceType
from pyangbind.lib.base import PybindBase
from collections import OrderedDict
from decimal import Decimal
from bitarray import bitarray
import six

# PY3 support of some PY2 keywords (needs improved)
if six.PY3:
  import builtins as __builtin__
  long = int
elif six.PY2:
  import __builtin__

class uis_rpl(PybindBase):
  """
  This class was auto-generated by the PythonClass plugin for PYANG
  from YANG module uis-rpl - based on the path /uis-rpl. Each member element of
  the container is represented as a class variable - with a specific
  YANG type.

  YANG Description: This module is an a first approach to a fully RPL YANG model
  """
  _pyangbind_elements = {}

  

